import type { UpgradeDefinition } from '../types/content';

export const UPGRADES: UpgradeDefinition[] = [
  // --- Tooling ---
  {
    id: 'better-prompts-1',
    name: 'Better Prompts I',
    category: 'tooling',
    description: 'Systematic prompt templates for your most common tasks.',
    flavorText: 'You finally stopped writing "write me a function that" and started writing actual specs.',
    cost: 200,
    effects: [{ type: 'multiplier', stat: 'qualityMultiplier', value: 0.08 }],
    oneTime: true,
    tags: ['prompting'],
  },
  {
    id: 'saved-context-blocks',
    name: 'Saved Context Blocks',
    category: 'tooling',
    description: 'Reusable context snippets that you paste into every session. Reduces drift.',
    flavorText: 'Copy. Paste. Pray the model remembers what repo it is in.',
    cost: 350,
    effects: [{ type: 'multiplier', stat: 'computeEfficiency', value: 0.12 }],
    oneTime: true,
    tags: ['prompting', 'compute'],
  },
  {
    id: 'session-snapshots',
    name: 'Session Snapshots',
    category: 'tooling',
    description: 'Serialized session state so you can resume exactly where you left off.',
    flavorText: 'Context windows are temporary. Snapshots are forever. Or until the file gets corrupted.',
    cost: 600,
    requires: ['saved-context-blocks'],
    effects: [
      { type: 'multiplier', stat: 'computeEfficiency', value: 0.08 },
      { type: 'multiplier', stat: 'debtGainRate', value: -0.05 },
    ],
    oneTime: true,
    tags: ['prompting', 'stability'],
  },

  // --- Automation ---
  {
    id: 'hook-runner',
    name: 'Hook Runner',
    category: 'automation',
    description: 'A lightweight hook chain that fires on every save, commit, and deploy.',
    flavorText: 'It runs on commit. It runs on push. It ran when you opened the file. Nobody is sure why.',
    cost: 400,
    effects: [{ type: 'multiplier', stat: 'automationLevel', value: 0.15 }],
    oneTime: true,
    tags: ['automation', 'hooks'],
  },
  {
    id: 'nightly-build-agent',
    name: 'Nightly Build Agent',
    category: 'automation',
    description: 'An agent that runs the build every night and files a ticket if something breaks.',
    flavorText: 'It files the ticket. You ignore the ticket. At least there is a record.',
    cost: 700,
    requires: ['hook-runner'],
    effects: [
      { type: 'multiplier', stat: 'automationLevel', value: 0.10 },
      { type: 'multiplier', stat: 'outageSeverity', value: -0.10 },
    ],
    oneTime: true,
    tags: ['automation', 'stability'],
  },
  {
    id: 'auto-triage-queue',
    name: 'Auto-Triage Queue',
    category: 'automation',
    description: 'Incoming events are scored and auto-routed. Low-stakes choices resolve themselves.',
    flavorText: 'It accepted a licensing agreement on your behalf. You are choosing to be fine with that.',
    cost: 1200,
    requires: ['nightly-build-agent'],
    effects: [
      { type: 'multiplier', stat: 'automationLevel', value: 0.15 },
    ],
    oneTime: true,
    tags: ['automation', 'events'],
    // NOTE: owning this upgrade enables the autoAcceptEnabled settings toggle
  },

  // --- Team ---
  {
    id: 'reviewer-agent',
    name: 'Reviewer Agent',
    category: 'team',
    description: 'A specialized sub-agent that reviews diffs before merge.',
    flavorText: 'It will catch your typos. It will not catch your architectural decisions. That is on you.',
    cost: 800,
    effects: [
      { type: 'multiplier', stat: 'qualityMultiplier', value: 0.10 },
      { type: 'multiplier', stat: 'debtGainRate', value: -0.08 },
    ],
    oneTime: true,
    tags: ['agents', 'quality', 'stability'],
  },
  {
    id: 'ops-goblin',
    name: 'Ops Goblin',
    category: 'team',
    description: 'Handles deployment plumbing, environment variables, and mysterious restarts.',
    flavorText: 'It lives in your CI pipeline. It asks for nothing. You owe it everything.',
    cost: 600,
    effects: [
      { type: 'multiplier', stat: 'burnRate', value: -0.08 },
      { type: 'multiplier', stat: 'stability', value: 0.10 },
    ],
    oneTime: true,
    tags: ['agents', 'infra'],
  },
  {
    id: 'qa-imp',
    name: 'QA Imp',
    category: 'team',
    description: 'A small dedicated agent for regression testing. Occasionally finds real bugs.',
    flavorText: 'It found seventeen edge cases in your date parser. You shipped anyway. The bugs are in production.',
    cost: 900,
    effects: [
      { type: 'multiplier', stat: 'outageSeverity', value: -0.15 },
      { type: 'multiplier', stat: 'qualityMultiplier', value: 0.08 },
    ],
    oneTime: true,
    tags: ['agents', 'stability', 'quality'],
  },

  // --- Product ---
  {
    id: 'better-onboarding',
    name: 'Better Onboarding',
    category: 'product',
    description: 'A three-step onboarding flow that actually explains what the product does.',
    flavorText: 'Users no longer leave on the first screen. They leave on the third. Progress.',
    cost: 500,
    effects: [
      { type: 'multiplier', stat: 'directMonetization', value: 0.10 },
      { type: 'multiplier', stat: 'reputationGain', value: 0.05 },
    ],
    oneTime: true,
    tags: ['product', 'growth'],
  },
  {
    id: 'pricing-page-test',
    name: 'Pricing Page Test',
    category: 'product',
    description: 'A/B test your pricing. You will learn something uncomfortable.',
    flavorText: 'The higher price converted better. You are still angry about this.',
    cost: 750,
    effects: [
      { type: 'multiplier', stat: 'directMonetization', value: 0.15 },
    ],
    oneTime: true,
    tags: ['product', 'monetization'],
  },
  {
    id: 'customer-feedback-loop',
    name: 'Customer Feedback Loop',
    category: 'product',
    description: 'A lightweight system that gets feedback from actual users and routes it somewhere you will see it.',
    flavorText: 'They told you exactly what they wanted. You built the other thing anyway. But now you have data.',
    cost: 650,
    effects: [
      { type: 'multiplier', stat: 'qualityMultiplier', value: 0.08 },
      { type: 'multiplier', stat: 'directMonetization', value: 0.08 },
    ],
    oneTime: true,
    tags: ['product', 'community'],
  },

  // --- Stability ---
  {
    id: 'rollback-script',
    name: 'Rollback Script',
    category: 'stability',
    description: 'One command to undo the last deploy. You will use it more than you expect.',
    flavorText: 'git revert is not a rollback script. This is a rollback script.',
    cost: 300,
    effects: [
      { type: 'multiplier', stat: 'outageSeverity', value: -0.20 },
    ],
    oneTime: true,
    tags: ['stability'],
  },
  {
    id: 'ci-guardrails',
    name: 'CI Guardrails',
    category: 'stability',
    description: 'Automated checks that block merges when coverage drops or build breaks.',
    flavorText: 'The pipeline rejected your commit. For once, that is a feature.',
    cost: 550,
    requires: ['rollback-script'],
    effects: [
      { type: 'multiplier', stat: 'debtGainRate', value: -0.12 },
      { type: 'multiplier', stat: 'stability', value: 0.08 },
    ],
    oneTime: true,
    tags: ['stability', 'quality'],
  },
  {
    id: 'error-monitoring',
    name: 'Error Monitoring',
    category: 'stability',
    description: 'Real-time error tracking. You will discover errors you did not know existed.',
    flavorText: 'It has been alerting for three hours. You are pretty sure it was always doing this.',
    cost: 450,
    effects: [
      { type: 'multiplier', stat: 'outageSeverity', value: -0.10 },
      { type: 'multiplier', stat: 'stability', value: 0.12 },
    ],
    oneTime: true,
    tags: ['stability', 'monitoring'],
  },

  // --- Growth ---
  {
    id: 'launch-thread-generator',
    name: 'Launch Thread Generator',
    category: 'growth',
    description: 'Templates and prompts for writing a launch post that actually gets read.',
    flavorText: 'Thread 1/12: I spent six months building something. Here is what I learned. (Nobody asked.)',
    cost: 400,
    effects: [
      { type: 'multiplier', stat: 'reputationGain', value: 0.15 },
      { type: 'multiplier', stat: 'hypeMultiplier', value: 0.10 },
    ],
    oneTime: true,
    tags: ['growth', 'hype'],
  },
  {
    id: 'meme-kit',
    name: 'Meme Kit',
    category: 'growth',
    description: 'A folder of templates for dev-adjacent memes. Effective. Undignified. Necessary.',
    flavorText: 'The meme got 400 likes. The serious product post got 12. You know what to do.',
    cost: 300,
    effects: [
      { type: 'multiplier', stat: 'hypeMultiplier', value: 0.15 },
      { type: 'flat', stat: 'reputation', value: 5 },
    ],
    oneTime: true,
    tags: ['growth', 'hype', 'community'],
  },
  {
    id: 'waitlist-flow',
    name: 'Waitlist Flow',
    category: 'growth',
    description: 'Collect emails before launch. Create artificial scarcity. Feel slightly gross about it.',
    flavorText: 'You have 800 signups and 12 paying users. The funnel is working. Technically.',
    cost: 250,
    effects: [
      { type: 'multiplier', stat: 'reputationGain', value: 0.10 },
      { type: 'multiplier', stat: 'directMonetization', value: 0.05 },
    ],
    oneTime: true,
    tags: ['growth', 'product'],
  },

  // --- Infra ---
  {
    id: 'cache-layer',
    name: 'Cache Layer',
    category: 'infra',
    description: 'Cache expensive inference calls. Compute drops. Latency drops. Something breaks.',
    flavorText: 'Cache invalidation is one of the two hard problems. You have solved neither.',
    cost: 800,
    effects: [
      { type: 'multiplier', stat: 'burnRate', value: -0.12 },
      { type: 'multiplier', stat: 'computeEfficiency', value: 0.10 },
    ],
    oneTime: true,
    tags: ['infra', 'compute'],
  },
  {
    id: 'cheaper-region',
    name: 'Cheaper Region',
    category: 'infra',
    description: 'Move your compute to a region that charges less. Latency may be a vibe.',
    flavorText: 'The P99 latency jumped to 800ms. The bill dropped by 30%. You are at peace.',
    cost: 600,
    effects: [
      { type: 'multiplier', stat: 'burnRate', value: -0.10 },
    ],
    oneTime: true,
    tags: ['infra'],
  },
  {
    id: 'spot-compute',
    name: 'Spot Compute',
    category: 'infra',
    description: 'Preemptible instances at a discount. Stateless workloads only. Definitely stateless.',
    flavorText: 'It got preempted mid-migration. You have learned something important about yourself.',
    cost: 1000,
    requires: ['cheaper-region'],
    effects: [
      { type: 'multiplier', stat: 'burnRate', value: -0.15 },
      { type: 'multiplier', stat: 'stability', value: -0.05 },
    ],
    oneTime: true,
    tags: ['infra'],
  },
];
